# Site settings
title: Wjq Blog
SEOTitle: Jackey’s Blog♉
header-img: img/about-bg.jpg
email: 18120411@bjtu.edu.cn
description: "关于程序与设计、旅行者与梦想家 | ,Programmer,Software Engineer，UX Designer | 这里是 @jackey王家祺 的个人博客，与你一起发现更大的世界。"
keyword: "王家祺, jackey王家祺, jackey, JackeyWang777, @JackeyWang777, 王家祺的博客, jackey Blog, 博客, 个人网站, 互联网, 机器学习, tensorflow,pytorch 深度学习, 设计"
url: "https://JackeyeyWang777.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/JackeyWang777/JackeyWang777.github.io.git" # you code repository

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
zhihu_username:     
github_username:    JackeyWang777
#facebook_username:  JackeyWang777
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: jackey

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]
gitalk:
  enable: true   #是否开启Gitalk评论
  clientID: 1151613a00f1ee695c95                          #生成的clientID
  clientSecret: 4959fc2efda418ae3c988031f9d139724e8c3469   #生成的clientSecret
  repo: JackeyWang777.github.io    #仓库名称
  owner: JackeyWang777    #github用户名
  admin: JackeyWang777
  distractionFreeMode: true #是否启用类似FB的阴影遮罩



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "When you want to give up, think about what makes you insist on here.<br>在你想要放弃的时候，想想是什么让你当初坚持走到了这里。<br><p align="right">Kobe·Bryant</p>"
sidebar-avatar: /img/jackey7.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 2              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "杨涵晨的博客",
        href: "https://jackyanghc.github.io/"
    }
    ,{
        title: "知乎",
        href: "https://www.zhihu.com/"
    }
    ,{
        title: "网易公开课",
        href: "http://open.163.com/"
    },{
        title: "网易云课堂",
        href: "https://study.163.com/"
    },{
        title: "慕课网",
        href: "http://www.imooc.com/"
    }
]
